// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ7jrRiYjJJKFdfZcOOQPE7QNYtuhh4kA',
    appId: '1:1048673319845:web:da4982728705b27e36864c',
    messagingSenderId: '1048673319845',
    projectId: 'jobseek-app',
    authDomain: 'jobseek-app.firebaseapp.com',
    storageBucket: 'jobseek-app.appspot.com',
    measurementId: 'G-HGP3R34GNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC0AiYIJB9M2wYe76WwfIG-sPR-cdgg1w',
    appId: '1:1048673319845:android:707e5844a38bfd8a36864c',
    messagingSenderId: '1048673319845',
    projectId: 'jobseek-app',
    storageBucket: 'jobseek-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzsNCV_5OfGgJvGXqU9kGSHQSmLu9bqiA',
    appId: '1:1048673319845:ios:866cdf90f1cc101036864c',
    messagingSenderId: '1048673319845',
    projectId: 'jobseek-app',
    storageBucket: 'jobseek-app.appspot.com',
    iosBundleId: 'com.example.jobseek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzsNCV_5OfGgJvGXqU9kGSHQSmLu9bqiA',
    appId: '1:1048673319845:ios:866cdf90f1cc101036864c',
    messagingSenderId: '1048673319845',
    projectId: 'jobseek-app',
    storageBucket: 'jobseek-app.appspot.com',
    iosBundleId: 'com.example.jobseek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ7jrRiYjJJKFdfZcOOQPE7QNYtuhh4kA',
    appId: '1:1048673319845:web:0e3a38ad804bd3a336864c',
    messagingSenderId: '1048673319845',
    projectId: 'jobseek-app',
    authDomain: 'jobseek-app.firebaseapp.com',
    storageBucket: 'jobseek-app.appspot.com',
    measurementId: 'G-DH7SNPT8DS',
  );
}
